### ISSUE TITLE
Translations for non-base langauge is set back to default for system option sets

### ISSUE THREAD

**Issue by INKUBIT** [MscrmTools/MsCrmTools.Translator#15]
Hi there,

we experience issues with translating system option set labels for additional languages. This is only happening for system option sets and for an additional installed language.

We have an instance with English as the base language and then German as an additional language installed. We use the easy translator to customize the english label and translate the english label into German.

The process of using the translator with XRMToolbox and exporting and importing the translations works perfectly fine. After the import the labels look fine and as desired.

But after some time (we are not able to tell when or what it triggers) the translated German system options set labels jump back to the default label.

This is happening already the second time in a project and we tried to figure out what it triggers. Code change, import or export of a solution etc. Nothing... it seems to happen out of the blue.

Do you have any clue by what this could be triggered?

**Comment by MscrmTools** [comment]
Hi, sorry to answer so late.
So, if I understand correctly, system optionsets labels are set back to base language, but this behavior does not happen because of the use of Easy Translator, right?
If so, can you confirm you apply translation in your dev organization, and not on the other ones (uat, live, etc.)?
I would search for some solution import from a system that does not have the translation for the German langugage

**Comment by INKUBIT** [comment]
Yes, it is not happening because of the easy translator. At least we think so.

Yes, we translate on dev, put it on test and then on prod.

Thanks for the hint! We need to test this behavior on a test system. We will keep you updated if we know anything new.
