### ISSUE TITLE
Forms Tabs, Form Sections and Forms Fields

### ISSUE THREAD

**Issue by MezMarianne** [MscrmTools/MsCrmTools.Translator#27]
When exporting translations and then trying to add translations to Tabs, Sections and Forms Fields, the Excel file turns the cell blue. The translations are ignored on import and the tool clearly states that cells with color will not be imported.
Is this a bug or a feature? Is it not possible to translate Tabs, Sections and Forms Fields with this tool?

The most important feature for me is the Forms Fields (labels on Forms). The other two can be extracted with the standard translation XML file. The Forms Fields can not.
![image](https://user-images.githubusercontent.com/59650849/71978505-d1961080-321b-11ea-97d3-f5e74d3a575a.png)

![image](https://user-images.githubusercontent.com/59650849/71978583-f8ecdd80-321b-11ea-91de-4569f90cebe0.png)

/Marianne

**Comment by MscrmTools** [comment]
Definitively a bug for the cell being blue.

As for translation, there is a known issue here you need to open the form, save and publish to see the changes from an end user perspective.

The translation should be visible in form editor after using the tool but not form end user.

This issue is under review currently

**Comment by MscrmTools** [comment]
Just did a new test and it seems fields are translated correctly.
It might need a browser cache refresh but it does work.

Please reopen if this is still an issue for you
