### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by SamueleNobile** [MscrmTools/MsCrmTools.Translator#50]
I was using this tool and it started give me this error
![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/101119139/157049440-047fb396-aae1-49b7-bf2d-2186a2f1b43f.png)

I did all the steps as the days before.
It returns the same error to all my colleagues.

**Comment by MscrmTools** [comment]
Can you also precise the version of the tool?

**Comment by SamueleNobile** [comment]
Hi @MscrmTools 
the version is 1.2022.2.18

I just checked and I confirm that there are not any extra line.

**Comment by MscrmTools** [comment]
The error you sent a screenshot of is for charts. Can you look for something different in this sheet?

**Comment by SamueleNobile** [comment]
Good morning @MscrmTools,
we changed few data in order to send the file to you.
Could you provide me a email to send the file to?

Thanks in advance

**Comment by MscrmTools** [comment]
Can you send it to tanguy92[@]gmail_dot_com (remove brackets and replace _dot_ by .

**Comment by MscrmTools** [comment]
@SamueleNobile ok I got your file but did not reproduced either the error message you sent first.
Can you send me the latest error screenshot that you have?

**Comment by stact** [comment]
Hi @MscrmTools  got same issue on Charts. How to check on a previous version? I can't rollback the update ^^

**Comment by MscrmTools** [comment]
Hi @stact, any chance I can get your file?
If you want to revert to a previous version, you can download and extract a [specific nuget package version](https://www.nuget.org/packages/MsCrmTools.Translator/) and replace the file in your Plugins folder

**Comment by stact** [comment]
Hi @MscrmTools thank you for the trick! 
Working with this previous version.
I sent you the file for investigation.

**Comment by MscrmTools** [comment]
@stact, Thank you for the file. 
I was able to parse it and import without any issue (except the fact that some charts does not exist on my target env)
I really don't know what is the problem here...
I know the answer is "no" but would it be possible to get an access to the environment to try importing the file to the faulty env ?

**Comment by stact** [comment]
Hi @MscrmTools yes sure, but we are not on online platform, let me send you a meeting for screen share ;)

**Comment by MscrmTools** [comment]
@stact if you are not online, then no interest. I would have liked to connect directly to debug code in real time

**Comment by MscrmTools** [comment]
So what is your version of CRM?

**Comment by stact** [comment]
Here the version @MscrmTools 
Microsoft Dynamics 365
Version 2104 (9.1.9.8) (DB 9.1.9.8) on-premises

**Comment by stact** [comment]
Could you share with us the procedure to debug the tool please?

**Comment by MscrmTools** [comment]
Download source code and open it with visual studio
Restore Nuget packages (right click on solution)
Configure the project for debug : https://www.xrmtoolbox.com/documentation/for-developers/debug/
Run the project
Connect to your organisation 
Import your file
Visual studio should stop where the null reference occurs 
Send me a screenshot of visual studio where the problem occurs

**Comment by arlassen** [comment]
Hi,
I have same issue when importing charts with English and Danish translations.
I believe I have most up-to-date versions with:
- XrmToolBox version is 1.2022.5.56.
- Easy Translator version is 1.2022.2.18.
- My environment is type Developer with database version 9.2.22063.00186.

I should fairly easy get it up and running in a Trial environment where you can get access to if needed. However, I will be offline and on holiday for the next weeks, so it should probably be after that. I do have a Trial that expires in 14 days, so that would probably not be relevant to use. Please give a shout if you want me to give access to this.

**Comment by MscrmTools** [comment]
@arlassen if you can reproduce on this trial env, then I'm interesting to get access info to this trial + your translation file. I can have a quick check today

**Comment by arlassen** [comment]
Good news, now it also works for me. Thanks for solving this :-)
